### PR TITLE
Added  copyright text to the footer

### PR DESCRIPTION
**Pull request by KWangechi**
I have adjusted the footer to fit all screen sizes.

1. max-width - 650px
image

2. max-width - 1000px
image

3. max-width - 1300px
image

### CODE REVIEW

**Comment by KWangechi** [comment]
Fixed Issue #8

**Comment by jahir-raihan** [comment]
@KWangechi Hello, Thanks for your contribution. Your code is working fine, but i think It's active date background is not working as expected, it should be in circle shape, but from your changes it changed to square shape again. Please check it again, everything else is good to go. 

From Original version: 

Screenshot 2023-09-05 at 10 40 56 AM

From Your version : 

Screenshot 2023-09-05 at 10 41 01 AM

**Comment by KWangechi** [comment]
Oh okay. lemme check it out

**Comment by KWangechi** [comment]
The issue is now fixed

image

**Comment by KWangechi** [comment]
The issue is now fixed

image

**Comment by jahir-raihan** [comment]
@KWangechi Well Done !. Keep Up the good work. A new issue will be open for download issue because of new footer. Check that out too!

**Pull request merged**
