### PR TITLE
Fixed hover effect on empty date blocks - Issue #1

### PR DESCRIPTION
**Pull request by devbytemehedi**
- Removed styles from empty blocks for a cleaner and more consistent look.
- Eliminated the outline color from the year input box to enhance visual coherence.
- Aligned the active day color with the hover color and default color schemes for improved consistency.
- Adjusted hover colors for better user experience.
- Utilized the "Live Sass Compiler" to monitor Sass files, ensuring real-time style updates.
- Incorporated "Prettier" for consistent and well-formatted code.
- Thoroughly followed the contribution guide to ensure compliance with project standards.
- The live deployed link is: [https://devbytemehedi.github.io/calendar-generator/](https://devbytemehedi.github.io/calendar-generator/)

By making these changes, your website should appear cleaner, more consistent, and easier on the eyes. The alignment of active day color with hover color and the removal of unnecessary styles from empty blocks will contribute to a more visually appealing user experience.

### CODE REVIEW

**Comment by jahir-raihan** [comment]
@devbytemehedi Hey, you did a great job by looking into it. But you've also deployed a version of your own on your github,  take a look and remove the `.github/workflow` file from your repository. Also this issue #1 Defines only hover effect on empty blocks. Other issues will be open soon for other fixes.  You can replace the hover styling as it was before. I will merge as soon as you remove the hover styling. 
And please do not use ChatGPT!.

**Comment by devbytemehedi** [comment]
@jahir-raihan Okay i will remove the  `.github/workflow` and only fix #1 . i will create a separate  pull request for visual improvements. I used chatgpt for bulletpoints, description was one big paragraph.

**Comment by devbytemehedi** [comment]
@jahir-raihan hey i [remove hover styling and .github folder](https://github.com/jahir-raihan/calendar-generator/pull/6/commits/faacd784287fd46fa12fd9b2d26c6defeaf1d77e)

**Comment by jahir-raihan** [comment]
@devbytemehedi I think you've used prettier on Javascript as well by accident. Can you fix that please.

**Comment by devbytemehedi** [comment]
hey @jahir-raihan  how about i add `.prettierignore` file in the root of the project with index.js inside and remove prettier formating will it okay ?

**Comment by jahir-raihan** [comment]
@devbytemehedi Sure!

**Comment by devbytemehedi** [comment]
is everything okay now ?

**Comment by jahir-raihan** [comment]
@devbytemehedi let me check.

**Comment by jahir-raihan** [comment]
@devbytemehedi  Great work. I'm merging it. Keep up the good work.

**Comment by jahir-raihan** [comment]
@devbytemehedi For your information,  emojis in commit messages are a not a good thing.

**Comment by devbytemehedi** [comment]
@jahir-raihan  thanks bro, i think emojis makes commit message more visually appealing.

**Comment by devbytemehedi** [comment]
@jahir-raihan  bro i wanted you opinion on this [vscode-theme](https://marketplace.visualstudio.com/items?itemName=devbytemehedi.clearview-dark) i made

**Comment by jahir-raihan** [comment]
@devbytemehedi Oh hey, I was wrong , you should keep the `.github/workflow` file, as it is responsible for deployment. Any way good work. Next time if you contribute, make sure to fetch commits from the master branch.  I will check your theme right away.

**Comment by jahir-raihan** [comment]
@devbytemehedi Would be great if you reduce the contrast ratio on colors. But thats a great work you've done.

**Comment by devbytemehedi** [comment]
@jahir-raihan thanks for your review bro. If you like this theme please recommend others.

**Pull request merged**
