### PR TITLE
Added a footer for the copyright text

### PR DESCRIPTION
**Pull request by KWangechi**

### CODE REVIEW

**Comment by jahir-raihan** [comment]
@KWangechi Always wrap text elements inside `p` or other text tags. Remember to compile the scss file. Do not use `px` value for any property except font size. I will add rule for font sizes using global variables.

**Comment by KWangechi** [comment]
Fixed the issue

**Comment by KWangechi** [comment]
image

Included a description of my changes

**Comment by jahir-raihan** [comment]
@KWangechi You are few commits behind of the main branch.

**Pull request closed without merging**
