### PR TITLE
Added off day colors for weekend

### LINKED ISSUE #28: Add offday colors or something closed colors on weekends
Our calendar can be more enhanced by adding indicating colors to weekends. 

Such as offday colors on weekends.

### PR DESCRIPTION
**Pull request by imbeshat**
### Added off day colors for weekend
image

### CODE REVIEW

**Comment by ahsan-abc** [comment]
@imbeshat  good  but the background collapse with other ,that not looking good and give dim  backgound color

**Comment by jahir-raihan** [comment]
@imbeshat Instead of giving background color, I would suggests to only change font colors for weekends.

**Comment by jahir-raihan** [comment]
@imbeshat This feature has been added already.

**Comment by imbeshat** [comment]
> @imbeshat This feature has been added already.

Closing this PR.

**Pull request closed without merging**
