### PR TITLE
Feature/cursor pointer

### PR DESCRIPTION
**Pull request by diegolikescode**
Hello, @jahir-raihan! Nice educative repo you have there, I made the changes mentioned in the issue #14 and improved a little of the documentation for those who may be lost in the ``SCSS`` conversion.

Thanks man, and happy learning!

### CODE REVIEW

**Comment by jahir-raihan** [comment]
@diegolikescode Let's make it more clear for our contributors, scss files can be compiled easily by using `VS` code extension `Watch Scss` ;).

**Comment by diegolikescode** [comment]
@jahir-raihan done! The extension that I found was originally called "DartJS Sass Compiler and Sass Watcher", but I named "Sass Watcher Extension" in the docs to avoid confusion. I hope it's good :pray:

**Comment by jahir-raihan** [comment]
@diegolikescode Hey, No need to mention the name of the extension, it is available on VS code , anyone can find it by searching.

**Comment by jahir-raihan** [comment]
@diegolikescode You can provide information like `To compile SCSS file to CSS, use any live SCSS compiler in VS code or any package of your reference`

**Comment by jahir-raihan** [comment]
@diegolikescode Hey life happens, I'm merging your work, you've put effort to make a pull request. That's amazing,  keep up the good work. We can fix the inconsistency and docs on later PRs.

**Comment by diegolikescode** [comment]
Thank you very much @jahir-raihan! Keep up the good learning as well!

**Comment by jahir-raihan** [comment]
@diegolikescode keep contributing ;)

**Pull request merged**
