### PR TITLE
Fixed the issue with hover effect on empty days

### PR DESCRIPTION
**Pull request by Axxi3**
I created another class called nonEmpty-Days which i added to the empty days

### CODE REVIEW

**Comment by devbytemehedi** [comment]
@Axxi3 read this [guide](https://github.com/jahir-raihan/calendar-generator/blob/master/CONTRIBUTION.md) to contribute 
- Do not edit RAW CSS files for styling, edit SCSS files instead.

**Comment by Axxi3** [comment]
okay I'll fix it

**Comment by devbytemehedi** [comment]
@Axxi3 it's already fixed and merged

**Comment by Axxi3** [comment]
okay

**Comment by diva-21** [comment]
> @Axxi3 it's already fixed and merged

but in the deployed version,the cursor is continously changing from pointer to normal ....

**Comment by jahir-raihan** [comment]
@diva-21 Hey diva , A new issue is opened for this problem, will be great to if you look into it.

**Comment by diva-21** [comment]
> @diva-21 Hey diva , A new issue is opened for this problem, will be great to if you look into it.

yup sure

**Pull request closed without merging**
