### PR TITLE
Fix : Issue #16

### PR DESCRIPTION
**Pull request by Sumonta056**

### CODE REVIEW

**Comment by jahir-raihan** [comment]
@Sumonta056 Providing some description about your changes will stand out and will be reviewed.

**Comment by Sumonta056** [comment]
1. Firstly added inline-block to .download  in index.scss
`.download {
    display: inline-block;
 }`

2.  Then added some properties in media query for phone screen
```code
@media only screen and (max-width: 650px) {
  .download-container {
    text-align: center; /* Center the button */
  }
  .download {
    font-size: 13px;  /* Reducing font size */
  }
}
```

**Comment by jahir-raihan** [comment]
@Sumonta056 If you set a fixed width for the download button, you could reduce the amount of code you've written. 
Eg: `.download{width:__px;}`

**Comment by Sumonta056** [comment]
I think there was already a fixed width set for the download button. 
```code
.download {
    width: 120px;
    padding: 0.5em 1em;
    height: 35px;
    font-size: 15px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
```

I just added "display: inline-block;" and some media query properties to the code to solve the issue..

**Comment by jahir-raihan** [comment]
@Sumonta056 Ok,  I'll let you know after testing it out.

**Comment by jahir-raihan** [comment]
@Sumonta056 Keep up the good work !

**Pull request merged**
