### PR TITLE
Added a download functionality to enable download of the calendar

### PR DESCRIPTION
**Pull request by KWangechi**
I have been able to add the download functionality to the calendar. I have used the html2canvas library to convert the calendar html element into an image then converted that canvas into a PDF file by defining it's width, height and margins.

The calendar is downloaded however the name of the months are not displayed in the calendar because the paper color of the PDF is white and the color for the month names is also white therefore they are not visible. Therefore I have changed the color and font-size in the SCSS class. 

However, the styling is not perfect as the numbers appear squeezed in the PDF file which can be improved. 

Below is the image of the PDF file downloaded:

image

### CODE REVIEW

**Comment by jahir-raihan** [comment]
@KWangechi Hey KWangechi , thanks for looking into it. I'll be back with feedback.

**Comment by jahir-raihan** [comment]
@KWangechi Did you followed the [Contribution Guide](https://github.com/jahir-raihan/calendar-generator/blob/master/CONTRIBUTION.md) !.

**Comment by KWangechi** [comment]
Yes yes I did.

**Comment by jahir-raihan** [comment]
@KWangechi Format Html and scss files using prettier. 
Also you've changed `year_month_name` - tag 'p' to a `div` I think this is not necessary. 

Also about the color while downloading as pdf. You can easily change the colors of year_month_names using javascript DOM,  and when download finishes you can revert them back to their original color.

**Comment by KWangechi** [comment]
Alright, let me make the necessary changes

**Comment by jahir-raihan** [comment]
@KWangechi Also a small reminder , you don't have to do all at once, do it with your own pace :). Happy Coding ;).

**Comment by jahir-raihan** [comment]
@KWangechi And if you found any bug, improvement or fixes, I encourage you to open a issue for that. Thanks.

**Comment by KWangechi** [comment]
Sure thing. I'm delighted to be contributing, it's my first time too.

Thank you😃

**Comment by KWangechi** [comment]
> @KWangechi And if you found any bug, improvement or fixes, I encourage you to open a issue for that. Thanks.

Alright. Will do

**Comment by KWangechi** [comment]
I have fixed the issues you had pointed out. I also removed the color change in the SCSS file for the download and done the DOM manipulation in the index.js file

**Comment by jahir-raihan** [comment]
@KWangechi **Looks Good to me**. Few issues are still visible , but I will open separate issues for those. You've done a great work. Appreciate your effort. **Be consistent**. I'm merging you're download feature. Tomorrow I will open a new issue for **pdf stretching issue**.

## A little improvement
> - **Also one thing to note, you've changed `year_month_name` colors while downloading inside download function, I'll suggest you to  change those colors to `theme black color` and align them left, also it will be great if you set the font size as it is to `13px`.**

> - **Open a separate pull request for this and try to fix them as well. Once again, great job ;).** 
I'm merging it !

Screenshot 2023-08-25 at 7 23 44 PM

**Pull request merged**
